name: Fetch and Commit JSON

on:
  schedule:
    - cron: '40 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch JSON using cURL
      run: |
        curl -X GET "https://api.citsci.org/projects/763e36aa-d485-425e-b2fd-05fffec0f5d3/observations" \
        -H "accept: application/ld+json" \
        -H "API-Key: ${{ secrets.API_KEY }}" \
        -o filename.json

    - name: Configure git
      run: |
        git config --global user.name 'emily-bodekerscientific'
        git config --global user.email 'emily@bodekerscientific.com'

    - name: Commit and Push
      run: |
        git add filename.json
        git diff --staged --exit-code || git commit -m "Update JSON"
        git push origin main

